---
title: "week2"
author: "Ronnie"
date: "2/6/2020"
output: github_document
---

```{r}
library(tidyverse)
library(lubridate)
library(e1071)
library(ggplot2)
```

## 3.1 Introduction

```{r}
sales <- read_csv(here::here("data/resale-flat-prices-based-on-registration-date-from-jan-2015-onwards.csv")) %>% 
  mutate(month = ymd(month, truncated = 1),
         flat_type = as_factor(flat_type),
         storey_range = as_factor(storey_range),
         flat_model = as_factor(flat_model))
```

```{r}
saveRDS(sales, here::here("data/sales.rds"))
```

```{r}
sales <- readRDS(here::here("data/sales.rds"))
```

## 3.2 Central Tendency

```{r}
manual_mode <- function(x, na.rm = FALSE) {
  if(na.rm){
    x = x[!is.na(x)]
  }

  ux <- unique(x)
  return(ux[which.max(tabulate(match(x, ux)))])
}
```

```{r}
mean(sales$floor_area_sqm)
```
```{r}
median(sales$floor_area_sqm)
```
```{r}
manual_mode(sales$floor_area_sqm)
```

## 3.3 Dispersion

```{r}
# Range
max(sales$floor_area_sqm) - min(sales$floor_area_sqm)

# Interquartile Range
IQR(sales$floor_area_sqm)

# Standard Deviation
sd(sales$floor_area_sqm)

# Coefficient of variation
sd(sales$floor_area_sqm) / mean(sales$floor_area_sqm)

# Kurtosis and Skewness from the 'e1071` library
kurtosis(sales$floor_area_sqm)
skewness(sales$floor_area_sqm)
```

```{r}
summary(sales$floor_area_sqm)
```

```{r}
skimr::skim(sales$floor_area_sqm)
```

## 3.4 Visualization

```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(binwidth = 5)
```

```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(aes(y = ..density..), binwidth = 5) +
  stat_function(fun = dnorm, args = list(mean = mean(sales$floor_area_sqm), sd = sd(sales$floor_area_sqm)))
```

```{r}
sales %>% 
  filter(floor_area_sqm == 67) %>% 
  View()
```

```{r}
ggplot(sales, aes(x = 1, y = floor_area_sqm)) + 
  geom_boxplot()
```

```{r}
ggplot(sales, aes(x = 1, y = floor_area_sqm)) + 
  geom_violin()
```

```{r}
ggplot(sales, aes(x = floor_area_sqm)) + 
  geom_histogram(binwidth = 10) +
  facet_wrap(vars(flat_type), scales = "free_y")
```

```{r}
ggplot(sales, aes(x = flat_type, y = floor_area_sqm)) + 
  geom_violin()
```

